### ISSUE TITLE
Input fields are breaking on change

### ISSUE THREAD

**Issue by Harshil-Jani** [CatsInTech/Rezume#83]
**Describe the bug**
The form components in which you would be providing your inputs are breaking on changing their state. As soon as you type, The components will vanish.
Make sure you are on localhost:3000 and not on https://app.rezyume.co/ because the input fields on live site are working well but, since then there have been many updates on the git repo which might be breaking those inputs.

**Expected behavior**
They should not vanish instead be supportive.

**Screenshots**
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/79367883/156405761-1c6c4a55-4b23-4d1b-88e2-23e4b0fe20ae.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Browser : Chrome

**Additional context**

**Comment by MitAbhay** [comment]
Assign this to me.

**Comment by praveenscience** [comment]
@MitAbhay go for it. Let's try looking at it tomorrow for updates...

**Comment by Shivansh-yadav13** [comment]
This issue needs to be fixed immediately otherwise contributors might not be able to add more changes
from what I'm able to see when we make a change in the form input the prop `CurrentPage` becomes `undefined` due to which we don't see the forms of that page.

https://github.com/CatsInTech/Rezume/blob/ef9f825a62b98a04e3118ba4bcd941978dc9d108/src/components/App.js#L34

In the above line, we need to also set the value of `CurrentPage` by
```
...appState, Resume: ...
```

@MitAbhay do let us know if you are facing any problems while fixing it.

**Comment by MitAbhay** [comment]
@Shivansh-yadav13, Oh sorry for being late, I have resolved the issue ...... only PR is left, Let me make that.

**Comment by MitAbhay** [comment]
@Shivansh-yadav13  Are you not going to tag the issues with the Gssoc2022 label, like in your previous year's issues?

**Comment by Shivansh-yadav13** [comment]
@MitAbhay I'm just a contributor 😅

**Comment by MitAbhay** [comment]
Ohk, I think I get confused 🙃

**Comment by MitAbhay** [comment]
Can you Clear it, @Harshil-Jani

**Comment by praveenscience** [comment]
@MitAbhay I have no clue what @Shivansh-yadav13 is trying to do! 😅
